[env.production]
routes = [
  { pattern = "krixum.com/*", custom_domain = true },
  { pattern = "krixum.ai/*", custom_domain = true }
]

[[headers]]
for = "/*"
[headers.values]
X-Frame-Options = "DENY"
X-Content-Type-Options = "nosniff"
Referrer-Policy = "strict-origin-when-cross-origin"